version: "3.8"

services:

  nginx:
    image: library/nginx:alpine
    container_name: fastapi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - auth_service
      - auth_db

  auth_db:
    image: library/postgres:12.0-alpine
    container_name: auth_db
    restart: always
    env_file:
      - auth/.env
    ports:
      - 5433:5432
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  auth_service:
    container_name: auth_service
    build: auth/.
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    depends_on:
      - auth_db
    env_file:
      - auth/.env

  main_service:
    container_name: main_service
    build: routes/.
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
    depends_on:
      - auth_db
      - main_db
    env_file:
      - routes/.env

  main_db:
    image: library/postgres:12.0-alpine
    container_name: main_db
    restart: always
    env_file:
      - routes/.env
    ports:
      - 5434:5432
    volumes:
      - main_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata:
  main_pgdata:

networks:
  default:
    name: fastapi-network
