"""create user table

Revision ID: cb0dfd1b5880
Revises: 
Create Date: 2022-06-29 00:13:08.791941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0dfd1b5880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True, comment='Почта пользователя'),
    sa.Column('first_name', sa.String(), nullable=True, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(), nullable=True, comment='Фамилия пользователя'),
    sa.Column('uuid', sa.String(), nullable=True, comment='uuid пользователя для связи с основной базой'),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='Хэшированный пароль'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
