"""Create base tables

Revision ID: 486a371e0899
Revises: 
Create Date: 2022-06-29 12:31:08.824983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486a371e0899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='Название точки маршрута'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Координата широты'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Координата долготы'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_index(op.f('ix_points_latitude'), 'points', ['latitude'], unique=False)
    op.create_index(op.f('ix_points_longitude'), 'points', ['longitude'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True, comment='Уникальный номер маршрута'),
    sa.Column('user_uuid', sa.String(), nullable=True, comment='uuid пользователя, создавшего маршрут'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'number', name='_user_uuid_number_uc')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('route_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False, comment='Связь с таблицей маршруты'),
    sa.Column('point_id', sa.Integer(), nullable=False, comment='Связь с таблицей точки'),
    sa.Column('sequence_number', sa.Integer(), nullable=True, comment='Порядковый номер точки на маршруте'),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_point')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_points_longitude'), table_name='points')
    op.drop_index(op.f('ix_points_latitude'), table_name='points')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_table('points')
    # ### end Alembic commands ###
